# Generated by Django 5.0.1 on 2024-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonName', models.CharField(max_length=255)),
                ('TotalMoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LeftMoney', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expName', models.CharField(max_length=255)),
                ('expDate', models.DateField()),
                ('paidPerson', models.CharField(max_length=255)),
                ('expContri', models.CharField(max_length=255)),
                ('expPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
