# Generated by Django 5.0.1 on 2024-01-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelsplit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='LeftMoney',
        ),
    ]
