# Generated by Django 5.0.1 on 2024-01-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsplit', '0002_remove_person_leftmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelexpense',
            name='expDate',
            field=models.CharField(max_length=255),
        ),
    ]
